### ISSUE TITLE
Druidic Spellcasting and Wild Shape

### ISSUE THREAD

**Issue by cwstra** [BTMorton/dnd-5e-srd#7]
The two sections mentioned seem to be pretty mixed up. I might try fixing it myself later, but thought I'd bring it up in the event someone else can get to it first.

**Comment by cwstra** [comment]
Similarly, I noticed that Alignment and Language Rules are part of the Multiclassing section.

**Comment by cwstra** [comment]
Found another one: Using Ability Scores has the Time, Movement, The Environment, Resting, and Between Adventures categories inside it.

**Comment by BTMorton** [comment]
Good spot, fixed 👍
